# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Configur VM
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "ubuntu-1404"
  config.vm.provison "chef_solo" do | chef |
    chef.add_recipe "base_install"
  end
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.name = "Customized Ubuntu"
  end
  config.vm.post_up_message = "enter \"vagrant ssh\" once updates are complete"

  # Configure Network
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 9443

  # NVim
  config.vm.provision :shell, inline: "add-apt-repository ppa:neovim-ppa/unstable -y"
  config.vm.provision :shell, inline: "apt-get -y install neovim"
  config.vm.provision :shell, inline: "update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60"
  config.vm.provision :shell, inline: "update-alternatives --config vi"
  config.vm.provision :shell, inline: "update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60"
  config.vm.provision :shell, inline: "update-alternatives --config editor"
end
